# Generated by Django 3.1.3 on 2020-12-01 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20201201_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='hunter',
            new_name='applicant',
        ),
    ]
